---
- hosts: test_centos
  remote_user: deploy
  vars:
      pypi_host: pypi.doubanio.com
  tasks:
    - name: update git
      git: repo={{ git_url }} dest=/var/www/{{ name }} version=develop accept_hostkey=True

    - name: update pip requirements
      pip: chdir=/var/www/{{ name }} requirements=requirements.txt virtualenv=/var/www/{{ name }}/venv
              extra_args='-i https://{{ pypi_host }}/simple/ --trusted-host {{ pypi_host }}'

    - name: restart uwsgi
      shell: /var/www/{{ name }}/venv/bin/uwsgi --reload /tmp/{{ name }}.pid
