repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-ast

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.4
    hooks:
      - id: autopep8

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        # exit code 5: no test files collected
        entry: bash -c 'pytest --cov=.; a="$?"; if [ "$a" == 5 ]; then exit 0; else exit $a; fi;'
        language: system
        pass_filenames: false
        always_run: true
